# Generated by Django 3.2.1 on 2023-06-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0002_userdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentdetaildb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('emaill', models.CharField(blank=True, max_length=30, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cartdb',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
