# Generated by Django 3.2.10 on 2023-06-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0003_auto_20230615_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetaildb',
            name='productname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetaildb',
            name='productprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetaildb',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetaildb',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
