# Generated by Django 3.2.10 on 2023-06-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0004_auto_20230616_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetaildb',
            name='zip',
        ),
    ]
