# Generated by Django 3.2.1 on 2023-06-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0005_remove_paymentdetaildb_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetaildb',
            name='address',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
