# Generated by Django 3.2.1 on 2023-06-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0006_paymentdetaildb_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetaildb',
            name='Month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetaildb',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetaildb',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetaildb',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetaildb',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
